"""Shared TriDB storage backend for long-context memory benchmarks.

This is deliberately a vector-only first adapter. It uses stock TriDB's
PostgreSQL + pgvector surface while preserving benchmark scope, source ids,
timestamps, roles, and metadata. Graph construction is left to a later
adapter so the first LongMemEval/LoCoMo results isolate the storage and
retrieval path from LLM-generated memory semantics.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any, Mapping, Protocol, Sequence

DEFAULT_DSN = "postgresql://postgres:tridb@localhost:5432/postgres"
DEFAULT_MODEL = "BAAI/bge-small-en-v1.5"
DEFAULT_DIM = 384
DEFAULT_TABLE = "agent_memory_units"

_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _checked_identifier(value: str) -> str:
    if not _IDENTIFIER.fullmatch(value):
        raise ValueError(f"unsafe SQL identifier: {value!r}")
    return value


def _vec_literal(embedding: Sequence[float]) -> str:
    return "[" + ",".join(repr(float(value)) for value in embedding) + "]"


class EmbeddingProvider(Protocol):
    def encode(self, texts: Sequence[str]) -> list[list[float]]: ...


class FastEmbedder:
    """Batched fastembed wrapper with no GPU requirement."""

    def __init__(
        self,
        model_name: str = DEFAULT_MODEL,
        *,
        batch_size: int = 64,
    ) -> None:
        from fastembed import TextEmbedding

        self.model_name = model_name
        self.batch_size = batch_size
        self._model = TextEmbedding(model_name=model_name)

    def encode(self, texts: Sequence[str]) -> list[list[float]]:
        if not texts:
            return []
        vectors = self._model.embed(list(texts), batch_size=self.batch_size)
        return [[float(value) for value in vector] for vector in vectors]


@dataclass(frozen=True)
class MemoryUnit:
    scope_id: str
    external_id: str
    content: str
    session_id: str | None = None
    kind: str = "turn"
    role: str | None = None
    event_time: str | None = None
    event_order: int = 0
    metadata: Mapping[str, Any] = field(default_factory=dict)
    embedding: Sequence[float] | None = None


@dataclass(frozen=True)
class SearchHit:
    id: int
    scope_id: str
    external_id: str
    session_id: str | None
    kind: str
    role: str | None
    content: str
    event_time: str | None
    event_order: int
    metadata: Mapping[str, Any]
    score: float


class TriDBMemoryBackend:
    """Scoped memory units over a single TriDB/pgvector table."""

    def __init__(
        self,
        conn: Any,
        *,
        dim: int = DEFAULT_DIM,
        table: str = DEFAULT_TABLE,
        embedder: EmbeddingProvider | None = None,
    ) -> None:
        if dim <= 0:
            raise ValueError("dim must be positive")
        self.conn = conn
        self.dim = dim
        self.table = _checked_identifier(table)
        self.embedder = embedder

    @classmethod
    def connect(
        cls,
        dsn: str = DEFAULT_DSN,
        *,
        dim: int = DEFAULT_DIM,
        table: str = DEFAULT_TABLE,
        embedder: EmbeddingProvider | None = None,
    ) -> TriDBMemoryBackend:
        import psycopg

        conn = psycopg.connect(dsn, autocommit=True)
        return cls(conn, dim=dim, table=table, embedder=embedder)

    @property
    def _quoted_table(self) -> str:
        return f'"{self.table}"'

    def close(self) -> None:
        self.conn.close()

    def init_schema(self) -> dict[str, Any]:
        """Create the benchmark table and cosine HNSW index idempotently."""
        self.conn.execute("CREATE EXTENSION IF NOT EXISTS vector")
        row = self.conn.execute(
            "SELECT atttypmod FROM pg_attribute"
            " WHERE attrelid = to_regclass(%s) AND attname = 'embedding'",
            (self.table,),
        ).fetchone()
        if row is not None and row[0] != self.dim:
            raise RuntimeError(
                f"existing {self.table}.embedding is vector({row[0]}), configured "
                f"dimension is {self.dim}"
            )

        table = self._quoted_table
        self.conn.execute(
            f"CREATE TABLE IF NOT EXISTS {table} ("
            " id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            " scope_id text NOT NULL,"
            " external_id text NOT NULL,"
            " session_id text,"
            " kind text NOT NULL,"
            " role text,"
            " content text NOT NULL,"
            " event_time text,"
            " event_order bigint NOT NULL DEFAULT 0,"
            " metadata jsonb NOT NULL DEFAULT '{}'::jsonb,"
            f" embedding vector({self.dim}) NOT NULL,"
            " created_at timestamptz NOT NULL DEFAULT now(),"
            " UNIQUE (scope_id, external_id))"
        )
        self.conn.execute(
            f'CREATE INDEX IF NOT EXISTS "{self.table}_scope_idx" ON {table} (scope_id)'
        )
        self.conn.execute(
            f'CREATE INDEX IF NOT EXISTS "{self.table}_session_idx"'
            f" ON {table} (scope_id, session_id)"
        )
        self.conn.execute(
            f'CREATE INDEX IF NOT EXISTS "{self.table}_embedding_hnsw"'
            f" ON {table} USING hnsw (embedding vector_cosine_ops)"
        )
        return {"ok": True, "table": self.table, "dim": self.dim}

    def _validate_vector(self, vector: Sequence[float]) -> list[float]:
        values = [float(value) for value in vector]
        if len(values) != self.dim:
            raise ValueError(
                f"embedding has {len(values)} dimensions, expected {self.dim}"
            )
        return values

    def _resolve_unit_vectors(self, units: Sequence[MemoryUnit]) -> list[list[float]]:
        vectors: list[list[float] | None] = []
        missing_positions: list[int] = []
        missing_texts: list[str] = []
        for position, unit in enumerate(units):
            if unit.embedding is None:
                vectors.append(None)
                missing_positions.append(position)
                missing_texts.append(unit.content)
            else:
                vectors.append(self._validate_vector(unit.embedding))

        if missing_positions:
            if self.embedder is None:
                raise RuntimeError(
                    "no embedder configured; provide MemoryUnit.embedding values"
                )
            generated = self.embedder.encode(missing_texts)
            if len(generated) != len(missing_positions):
                raise RuntimeError(
                    "embedder returned a different number of vectors than inputs"
                )
            for position, vector in zip(missing_positions, generated, strict=True):
                vectors[position] = self._validate_vector(vector)

        return [vector for vector in vectors if vector is not None]

    def replace_scope(
        self,
        scope_id: str,
        units: Sequence[MemoryUnit],
        *,
        isolated: bool = True,
    ) -> int:
        """Atomically replace one corpus.

        ``isolated=True`` truncates this adapter's dedicated benchmark table.
        That matches LongMemEval's per-question corpus and LoCoMo's
        per-conversation corpus without HNSW tombstone accumulation.
        ``isolated=False`` preserves other scopes to exercise filtered ANN.
        """
        for unit in units:
            if unit.scope_id != scope_id:
                raise ValueError(
                    f"unit {unit.external_id!r} belongs to scope "
                    f"{unit.scope_id!r}, expected {scope_id!r}"
                )
        vectors = self._resolve_unit_vectors(units)
        table = self._quoted_table
        rows = [
            (
                unit.scope_id,
                unit.external_id,
                unit.session_id,
                unit.kind,
                unit.role,
                unit.content,
                unit.event_time,
                unit.event_order,
                json.dumps(dict(unit.metadata), sort_keys=True),
                _vec_literal(vector),
            )
            for unit, vector in zip(units, vectors, strict=True)
        ]

        with self.conn.transaction():
            if isolated:
                self.conn.execute(f"TRUNCATE TABLE {table}")
            else:
                self.conn.execute(
                    f"DELETE FROM {table} WHERE scope_id = %s", (scope_id,)
                )
            if rows:
                with self.conn.cursor() as cursor:
                    cursor.executemany(
                        f"INSERT INTO {table} ("
                        " scope_id, external_id, session_id, kind, role, content,"
                        " event_time, event_order, metadata, embedding)"
                        " VALUES (%s, %s, %s, %s, %s, %s, %s, %s,"
                        "         %s::jsonb, %s::vector)"
                        " ON CONFLICT (scope_id, external_id) DO UPDATE SET"
                        " session_id = EXCLUDED.session_id,"
                        " kind = EXCLUDED.kind,"
                        " role = EXCLUDED.role,"
                        " content = EXCLUDED.content,"
                        " event_time = EXCLUDED.event_time,"
                        " event_order = EXCLUDED.event_order,"
                        " metadata = EXCLUDED.metadata,"
                        " embedding = EXCLUDED.embedding",
                        rows,
                    )
        return len(rows)

    def delete_scope(self, scope_id: str) -> int:
        cursor = self.conn.execute(
            f"DELETE FROM {self._quoted_table} WHERE scope_id = %s",
            (scope_id,),
        )
        return cursor.rowcount

    def search(
        self,
        scope_id: str,
        *,
        query_text: str | None = None,
        query_embedding: Sequence[float] | None = None,
        k: int = 10,
    ) -> list[SearchHit]:
        if k <= 0:
            raise ValueError("k must be positive")
        if query_embedding is None:
            if query_text is None:
                raise ValueError("query_text or query_embedding is required")
            if self.embedder is None:
                raise RuntimeError("no embedder configured for query_text")
            encoded = self.embedder.encode([query_text])
            if len(encoded) != 1:
                raise RuntimeError("embedder did not return exactly one query vector")
            vector = self._validate_vector(encoded[0])
        else:
            vector = self._validate_vector(query_embedding)
        literal = _vec_literal(vector)

        # Scope is a correctness predicate. Iterative scan prevents selective
        # post-filtering from silently returning fewer than k rows.
        self.conn.execute("SET hnsw.iterative_scan = strict_order")
        rows = self.conn.execute(
            "SELECT id, scope_id, external_id, session_id, kind, role, content,"
            " event_time, event_order, metadata,"
            f" embedding <=> %s::vector AS distance FROM {self._quoted_table}"
            " WHERE scope_id = %s"
            " ORDER BY embedding <=> %s::vector LIMIT %s",
            (literal, scope_id, literal, k),
        ).fetchall()
        hits = []
        for row in rows:
            metadata = row[9]
            if isinstance(metadata, str):
                metadata = json.loads(metadata)
            hits.append(
                SearchHit(
                    id=row[0],
                    scope_id=row[1],
                    external_id=row[2],
                    session_id=row[3],
                    kind=row[4],
                    role=row[5],
                    content=row[6],
                    event_time=row[7],
                    event_order=row[8],
                    metadata=metadata,
                    score=1.0 - float(row[10]),
                )
            )
        return hits

    def count_scope(self, scope_id: str) -> int:
        return self.conn.execute(
            f"SELECT count(*) FROM {self._quoted_table} WHERE scope_id = %s",
            (scope_id,),
        ).fetchone()[0]
