-- Governed Evolving Memory (GEM) on TriDB — M_t = (D_t, S_t, P_t).
--
-- Orogat & Mansour, "Is Agent Memory a Database?" (arXiv:2605.26252v1) realise
-- GEM on Kuzu and call that substrate "a compatibility layer, not a native
-- expression of GEM", listing what a native engine would provide:
--   (i)   co-locate topics, field histories and embeddings on pages
--   (ii)  ONE physical organisation serving semantic, temporal and structural
--         queries without duplicating data
--   (iii) retrieval as a WRITE — an operator unifying search, traversal,
--         temporal lookup and salience update
-- This schema targets (ii) and (iii) on stock PostgreSQL + pgvector +
-- graph_store_am + tjs_pg. (i) is the CSR-lite page-layout work and is out of
-- scope here.
--
-- Placeholder: :dim (embedding dimension), substituted by
-- GemStore.init_schema(). Table names are fixed at the gem_ prefix; the
-- operators reference them by name, so this file is not parameterised on it.

-- ===========================================================================
-- D_t — content
-- ===========================================================================

-- A semantic unit ("topic"): self-contained, holding every field of one
-- concept. id MUST equal the native graph vid — tjs_open's graph leg resolves
-- a reach vertex with `SELECT <vec> FROM <tbl> WHERE <id_col> = $1` passing the
-- raw vid, so ids are allocated from graph_store.gph_allocated_vids().
CREATE TABLE IF NOT EXISTS gem_unit (
    id            bigint PRIMARY KEY,
    scope_id      text        NOT NULL,
    title         text        NOT NULL,
    summary       text        NOT NULL DEFAULT '',
    embedding     vector(:dim) NOT NULL,
    state         text        NOT NULL DEFAULT 'active'
                  CHECK (state IN ('active','compressed','hidden','archived')),
    salience      double precision NOT NULL DEFAULT 0,
    access_count  bigint      NOT NULL DEFAULT 0,
    last_access   timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    metadata      jsonb       NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (scope_id, title)
)
-- C6 makes EVERY retrieval a write (salience, access_count, last_access — none
-- of them indexed). Measured on 2,000 units x 200 updates: at the default
-- fillfactor=100 only 84% of those updates are heap-only (HOT) and the relation
-- grows; at 70 it is 100% HOT and costs ZERO bytes, so the salience write never
-- touches the HNSW index. See docs/agent_memory_gem_interface_v0.1.0.md §6.3.
WITH (fillfactor = 70);

-- Field value history H_{i,j} = <(v, t, pi)>. Updates APPEND; the prior value
-- is retained as historical evidence rather than overwritten.
CREATE TABLE IF NOT EXISTS gem_field_value (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id        bigint NOT NULL REFERENCES gem_unit(id) ON DELETE CASCADE,
    field          text   NOT NULL,
    value          text   NOT NULL,
    valid_from     timestamptz NOT NULL,
    valid_to       timestamptz,                 -- NULL = current (C1)
    superseded_by  bigint REFERENCES gem_field_value(id),
    -- provenance pi (C4) — preserved across revision and forgetting
    source_external_ids text[],
    source_unit_ids     bigint[],
    extractor_model     text,
    prompt_version      text,
    confidence          double precision,
    operator            text,
    transition_id       bigint,
    created_xid         xid8 NOT NULL DEFAULT pg_current_xact_id(),
    -- sub-unit salience: "part of a unit may be attenuated while the rest
    -- stays current", so the ladder is applied per field, not per topic
    salience       double precision NOT NULL DEFAULT 0,
    state          text NOT NULL DEFAULT 'active'
                   CHECK (state IN ('active','compressed','hidden','archived')),
    embedding      vector(:dim)                 -- optional fact-grain vector
)
-- Same reason as gem_unit: per-field salience rises on every access (C6).
WITH (fillfactor = 70);

-- *** C1 / Observation 3a, enforced by the engine rather than by convention ***
-- Observation 3a: "Append-only storage without semantic units cannot satisfy
-- C2. Two appended values for the same fact coexist with EQUAL STATUS, and a
-- default query has no engine-level mechanism to select between them."
-- This partial unique index IS that mechanism: at most one current value per
-- (unit, field) can exist, so a default query cannot be ambiguous and a
-- revision that would leave two current values ABORTS at commit.
CREATE UNIQUE INDEX IF NOT EXISTS gem_field_value_current_uq
    ON gem_field_value (unit_id, field)
    WHERE valid_to IS NULL AND state <> 'archived';

CREATE INDEX IF NOT EXISTS gem_field_value_unit_idx ON gem_field_value (unit_id);
CREATE INDEX IF NOT EXISTS gem_field_value_hist_idx
    ON gem_field_value (unit_id, field, valid_from DESC);
CREATE INDEX IF NOT EXISTS gem_unit_scope_idx  ON gem_unit (scope_id);
CREATE INDEX IF NOT EXISTS gem_unit_active_idx ON gem_unit (scope_id, state);
-- The routing vector. Cosine, matching the rest of bench/agent_memory; the MCP
-- server's l2 index is the odd one out and is migrated by the same change.
CREATE INDEX IF NOT EXISTS gem_unit_hnsw
    ON gem_unit USING hnsw (embedding vector_cosine_ops);

-- ===========================================================================
-- S_t — structure
-- ===========================================================================
--
-- TOPOLOGY LIVES IN THE NATIVE GRAPH AM, never in a relational join table
-- (CLAUDE.md rule 3). This table holds relational METADATA about edges the AM
-- cannot carry: the propagation right, the relation name, and the co-access
-- counter that retrieval strengthens.
--
-- The extension/association split is load-bearing for C3: "propagation must
-- follow entailment, not relatedness, so revision traverses extension edges
-- only. Association edges support retrieval context expansion without
-- propagation." Register them as separate native edge types so the operator
-- can traverse one kind without seeing the other:
--     graph_store.register_edge_type('extension')
--     graph_store.register_edge_type('association')
--
-- EXACTLY TWO native types, and the relation name (`moved_to`, `part_of`, ...)
-- stays in `rel` below. tjs_open / gph_traverse_typed take a SINGLE type id
-- (0 = ANY), not a set, so registering a native type per rel would make "all
-- extension edges regardless of rel" inexpressible against an equality filter.
-- With two types: extension-only (C3), association-only, and both (ANY) all
-- work with zero engine change. Verified live; see
-- docs/agent_memory_gem_interface_v0.1.0.md §6.1.
CREATE TABLE IF NOT EXISTS gem_edge (
    src             bigint NOT NULL REFERENCES gem_unit(id) ON DELETE CASCADE,
    dst             bigint NOT NULL REFERENCES gem_unit(id) ON DELETE CASCADE,
    edge_type       integer NOT NULL,          -- graph_store.edge_type.id
    kind            text NOT NULL CHECK (kind IN ('extension','association')),
    rel             text NOT NULL,
    weight          double precision NOT NULL DEFAULT 1.0,
    co_access_count bigint NOT NULL DEFAULT 0, -- C6 "updates memory structure"
    created_at      timestamptz NOT NULL DEFAULT now(),
    tombstoned_at   timestamptz,
    PRIMARY KEY (src, dst, edge_type)
);
CREATE INDEX IF NOT EXISTS gem_edge_kind_idx ON gem_edge (src, kind)
    WHERE tombstoned_at IS NULL;

-- ===========================================================================
-- P_t — policies, living INSIDE the state (Definition 3)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS gem_policy (
    name       text PRIMARY KEY,
    scope_id   text,                            -- NULL = global
    event      text NOT NULL
               CHECK (event IN ('field_updated','unit_ingested','retrieval','tick')),
    condition  jsonb NOT NULL,
    action     jsonb NOT NULL,
    enabled    boolean NOT NULL DEFAULT true,
    version    integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ===========================================================================
-- The trajectory {M_t} — the correctness object itself
-- ===========================================================================
--
-- "Correctness is a property of the trajectory, not of any individual record."
-- The research agenda asks for a trajectory benchmark with ground truth at
-- three levels: the current value of each unit over time (C2), the dependent
-- units that change after each update (C3), and the active footprint at each
-- interaction count (C5). This log carries all three.
--
-- It doubles as the Omri et al. §3.3 phase-event stream, so ONE record serves
-- both papers: `phase` + the token/call/latency columns are exactly what their
-- profiler attributes to construction / retrieval / generation.
CREATE TABLE IF NOT EXISTS gem_transition (
    t                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_id           text NOT NULL,
    operator           text NOT NULL
                       CHECK (operator IN ('ingest','revise','forget','retrieve')),
    phase              text NOT NULL,
    committed          boolean NOT NULL,
    aborted_reason     text,
    policies_evaluated text[],
    delta              jsonb NOT NULL DEFAULT '{}'::jsonb,
    -- C5: |D_t^active| <= beta(n), sampled after every transition
    active_units       integer,
    active_fields      integer,
    -- Omri phase telemetry
    seconds            double precision,
    llm_calls          integer NOT NULL DEFAULT 0,
    embed_calls        integer NOT NULL DEFAULT 0,
    embed_sequences    integer NOT NULL DEFAULT 0,
    prompt_tokens      bigint  NOT NULL DEFAULT 0,
    completion_tokens  bigint  NOT NULL DEFAULT 0,
    embed_input_tokens bigint  NOT NULL DEFAULT 0,
    db_statements      integer NOT NULL DEFAULT 0,
    gpu_joules         double precision,        -- NULL until the NVML sampler lands
    xid                xid8 NOT NULL DEFAULT pg_current_xact_id(),
    at                 timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS gem_transition_scope_idx ON gem_transition (scope_id, t);
