"""Generate a self-contained ALE-Bench evaluator for one AHC problem.

The corpus ships an `evaluate.py` per ALE run, but it imports
`benchmarks.ale_bench.ale_session_helper` from SkyDiscover, which is not published.
The scoring contract it implements is short enough to restate against `ale_bench`
directly, which IS installable, so that is what this generates.

    python3 -m tools.evotrace.ale_evaluator --problem ahc024 --out /tmp/eval_ahc024.py

Scoring follows the corpus evaluator exactly: evaluate the first `num_cases` public
cases, and take `overall_absolute_score / num_cases`, signed so that larger is better
regardless of whether the problem minimises or maximises. A non-ACCEPTED verdict on a
minimising problem scores the floor rather than a small number, because a rejected
submission is not a good one that happens to score low.

Environment the generated file depends on (see docs/INSTALL_ale_bench.md):
    DOCKER_HOST=unix:///run/user/<uid>/podman/podman.sock
    ALE_BENCH_DATA=<local copy of SakanaAI/ALE-Bench>
    ALE_BENCH_NO_CONTAINER_USER=1
"""

from __future__ import annotations

import argparse
from pathlib import Path

TEMPLATE = '''"""Generated by tools/evotrace/ale_evaluator.py -- do not edit.

ALE-Bench evaluator for {problem}, restated against `ale_bench` directly because the
corpus evaluator imports a SkyDiscover helper that was never published.
"""

import os
import sys

PROBLEM = {problem!r}
NUM_CASES = {num_cases}
LANGUAGE = {language!r}
WORKERS = {workers}

os.environ.setdefault("ALE_BENCH_NO_CONTAINER_USER", "1")
# Point at the rootless podman socket HERE rather than trusting the environment
# to arrive intact. Measured mid-run: 8 of 10 live cells had lost DOCKER_HOST
# even though the matrix process still carried it, and `docker.from_env()` then
# falls back to /var/run/docker.sock, which does not exist on this host -- every
# evaluation returns combined_score=0.0 with a DockerException and the cell reads
# as "the agent never improved". The evaluator is the only place that actually
# needs the socket, so it is the only place that should have to know the path.
if "DOCKER_HOST" not in os.environ:
    _sock = f"/run/user/{{os.getuid()}}/podman/podman.sock"
    if os.path.exists(_sock):
        os.environ["DOCKER_HOST"] = f"unix://{{_sock}}"


def _strip_markers(code):
    """Drop the harness's block markers.

    They are written with Python comment syntax even inside a .cpp file, so the C++
    compiler sees `# EVOLVE-BLOCK-START` and fails at the link step with no error
    message pointing anywhere useful.
    """
    return "\\n".join(l for l in code.splitlines() if "EVOLVE-BLOCK" not in l)


def evaluate(program_path):
    import ale_bench
    from ale_bench.result import JudgeResult

    session = None
    try:
        code = _strip_markers(open(program_path).read())
        session = ale_bench.start(problem_id=PROBLEM, lite_version=True,
                                  num_workers=WORKERS)
        sign = 1 if session.problem.metadata.score_type == "maximize" else -1
        result = session.case_eval(
            session.case_gen(list(range(NUM_CASES))), code,
            code_language=LANGUAGE, skip_local_visualization=True,
        )
        accepted = result.overall_judge_result == JudgeResult.ACCEPTED
        score = result.overall_absolute_score * sign / NUM_CASES
        if not accepted and sign == -1:
            # A rejected submission on a minimising problem must not read as a good
            # low score; it is the floor.
            score = -sys.maxsize - 1
        worst = result.case_results[0]
        for case in result.case_results:
            if case.judge_result == result.overall_judge_result:
                worst = case
                break
        return {{
            "combined_score": float(score),
            "judge_result": result.overall_judge_result.value,
            "overall_score": float(result.overall_absolute_score),
            "max_execution_time_sec": max(c.execution_time for c in result.case_results),
            "max_memory_usage_mib": max(c.memory_usage for c in result.case_results) // 1024 // 1024,
            "standard_error": (worst.error_str or "")[:2000],
            # `error_str` is the PROGRAM's stderr and is empty for a compile
            # failure, so a COMPILATION_ERROR came back with no text at all and
            # was indistinguishable from an environment fault (a real one earlier
            # in this work: an unwritable /workdir failed the link step silently).
            # `message` is where ale_bench puts the judge's own diagnostic.
            "judge_message": (getattr(worst, "message", "") or "")[:2000],
        }}
    except Exception as exc:  # noqa: BLE001
        return {{"combined_score": 0.0, "error": f"{{type(exc).__name__}}: {{exc}}"}}
    finally:
        if session is not None:
            try:
                session.close()
            except Exception:  # noqa: BLE001, S110
                pass
'''


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--problem", required=True, help="e.g. ahc024")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument(
        "--num-cases", type=int, default=10,
        help="public cases per evaluation. The corpus used 50; 10 keeps a single "
             "evaluation inside the wrapper's deadline while still averaging over "
             "enough cases that one unlucky instance cannot decide the score.",
    )
    ap.add_argument("--language", default="cpp20")
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args(argv)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        TEMPLATE.format(problem=args.problem, num_cases=args.num_cases,
                        language=args.language, workers=args.workers),
        encoding="utf-8",
    )
    print(f"{args.problem} -> {args.out} ({args.num_cases} cases, {args.language})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
