"""Wrap a task's evaluator so a runaway program can actually be killed.

OpenEvolve's timeout does not stop anything. `evaluator.py:351` runs the evaluation
with `loop.run_in_executor(None, ...)` and `evaluator.py:354` bounds it with
`asyncio.wait_for`. That cancels the awaitable, but a thread already executing in an
executor cannot be cancelled -- the evaluator keeps running forever, holding its
worker. Two such leaks and the pool is exhausted: the run goes silent at whatever
iteration it reached, reports `status: complete`, and produces no data.

Observed on four tasks across three attempts, always the same shape: "Evaluation timed
out after Ns" exactly twice, then hours of silence at iteration 0.

The fix is to make the evaluation killable. This generates a drop-in `evaluate.py`
that runs the real evaluator in a SUBPROCESS with its own hard deadline, kills the
process group on expiry, and returns a normal zero-score result. OpenEvolve's own
timeout then never fires, because ours resolves first and returns cleanly.

    python3 -m tools.evotrace.wrap_evaluator \
        --evaluator data/evotrace/raw/.../evaluate.py --timeout 240 --out /tmp/wrapped.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

TEMPLATE = '''"""Generated by tools/evotrace/wrap_evaluator.py -- do not edit.

Runs {evaluator} in a subprocess with a {timeout}s hard deadline.
"""

import json
import os
import signal
import subprocess
import sys
import tempfile

REAL = {evaluator!r}
TIMEOUT = {timeout}

_DRIVER = """
import importlib.util, json, sys
spec = importlib.util.spec_from_file_location("real_evaluator", sys.argv[1])
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
fn = getattr(module, sys.argv[3])
print("@@RESULT@@" + json.dumps(fn(sys.argv[2])))
"""


def _call(stage, program_path):
    with tempfile.TemporaryDirectory() as tmp:
        try:
            proc = subprocess.run(
                [sys.executable, "-c", _DRIVER, REAL, program_path, stage],
                capture_output=True, text=True, timeout=TIMEOUT, cwd=tmp,
                # Own process group: killing the parent is not enough when the
                # evaluator spawns children of its own, and an orphaned child keeps
                # burning a core for the rest of the run.
                start_new_session=True,
            )
        except subprocess.TimeoutExpired as exc:
            if exc.__dict__.get("pid"):
                try:
                    os.killpg(exc.pid, signal.SIGKILL)
                except (ProcessLookupError, PermissionError):
                    pass
            return {{"combined_score": 0.0, "error": "wrapped_timeout",
                     "timeout_seconds": TIMEOUT}}
        except Exception as exc:  # noqa: BLE001
            return {{"combined_score": 0.0, "error": f"{{type(exc).__name__}}: {{exc}}"}}

    marker = "@@RESULT@@"
    line = next((x for x in proc.stdout.splitlines() if x.startswith(marker)), None)
    if line is None:
        tail = (proc.stderr or "").strip().splitlines()[-1:] or [""]
        return {{"combined_score": 0.0, "error": f"evaluator_failed: {{tail[0][:200]}}"}}
    return json.loads(line[len(marker):])


def evaluate(program_path):
    return _call("evaluate", program_path)
'''


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--evaluator", type=Path, required=True)
    ap.add_argument("--timeout", type=int, default=240)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args(argv)

    evaluator = args.evaluator.resolve()
    if not evaluator.is_file():
        raise SystemExit(f"no evaluator at {evaluator}")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        TEMPLATE.format(evaluator=str(evaluator), timeout=args.timeout),
        encoding="utf-8",
    )
    print(f"wrapped {evaluator} -> {args.out} (timeout {args.timeout}s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
